[package]
name = "weather"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.90"
reqwest = { version = "0.11", features = ["blocking", "json"] }
chrono = "0.4.20"
serde-xml-rs = "0.6.0"